#!/bin/bash

. ./common.sh
echo DIMENSIONALITY is  $DIM

#GENDAT=`echo $PWD  | sed -r "s/src_(.*)\//src_CUDA\//"`
#if [ ! -f ${GENDAT}/genMackeyGlass.x ]; then
#   echo "File not found"
#   (cd ${GENDAT}; make genMackeyGlass.x genScale.x doSCALE.x)
#fi
GENDAT=.

B=0.1
C=0.2
M=3
DELTA=6
TAU=17
NPRED=100
SEED1=1234
SEED2=2346
SIZE=25000
rm -f train.dat

$GENDAT/genMackeyGlass.x - $SIZE $B $C $TAU $M $DELTA $SEED1 \
   | $GENDAT/doScale.x -0.9 0.9 \
   > train.dat

$GENDAT/genMackeyGlass.x - $NPRED $B $C $TAU $M $DELTA $SEED2 \
   | $GENDAT/doScale.x -0.9 0.9 \
   > pred.dat

