#!/bin/bash

. ./common.sh
echo DIMENSIONALITY is  $DIM

TIME=10 #seconds
NPRED=100
SEED1=1234
SEED2=123
SIZE=240000000
rm -f train.dat param.dat
./genData.x - $SIZE 0.01 $SEED1 $DIM | ./nloptTrain.x - param.dat $TIME
./genData.x - $NPRED 0 $SEED2 $DIM | ./pred.x - param.dat  > pred.csv
