#!/bin/bash

. ./common.sh

B=0.1
C=0.2
TAU=17
NPRED=100
SEED1=1234
SIZE=30000000

SCALE_SIZE=`expr $SIZE \* 10`
echo "Finding min and max for examples=" $SCALE_SIZE
./genMackeyGlass.x - $SIZE $B $C $TAU $DIM $SEED1 \
   | ./genScale.x - > scale.hpp
