if [ -z "$1" ];then
 echo "Specify the input vector length"
 exit -1
fi
# specify the size of the input vector in common.sh
echo "DIM="$1 > common.sh

#specify the input vector size in FcnOfInterest.h
echo "//This file generated by DEFINE_INPUTSIZE.sh" > InputSize.h
echo "#define N_INPUT $1" >> InputSize.h


make clean; 
make -j

