#!/bin/bash

. ./common.sh
echo DIMENSIONALITY is  $DIM

NPRED=100
SEED1=1234
SEED2=123
SIZE=30000000
rm -f train.dat param.dat
gcc genData.cc -o a.out.x
./a.out.x train.dat $SIZE 0.01 $SEED1 $DIM
rm a.out.x
