#!/bin/bash

. ./common.sh
echo DIMENSIONALITY is  $DIM

rm -f train.dat
GENDAT=`echo $PWD  | sed -r "s/src_(.*)\//src_OMP\//"`
if [ ! -f ${GENDAT}/genMackeyGlass.x ]; then
   echo "File not found"
   (cd ${GENDAT}; make genMackeyGlass.x)
fi

B=0.1
C=0.2
TAU=17
NPRED=100
SEED1=1234
SIZE=30000000
rm -f train.dat param.dat
$GENDAT/genMackeyGlass.x train.dat $SIZE $B $C $TAU $DIM $SEED1 

